apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        # -------------------------------------------------
        # !!! IMPORTANT !!! 
        # CHANGE THE LINE BELOW to your Docker Hub username
        # -------------------------------------------------
        image: chadalanlester/hello-app:v1 
        ports:
        - containerPort: 8080
